name: C++ CI Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch (change as needed)
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ build environment
        uses: actions/setup-cpp@v1
        with:
          compiler: 'gcc'  # You can also use 'clang' or another compiler

      - name: Compile C++ code
        run: |
          g++ test.cpp -o test_executable 

      - name: Run the compiled program
        run: |
          ./test_executable  
        continue-on-error: true  # Ensure workflow doesn't fail if execution fails

      - name: Archive the executable as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-executable
          path: test_executable 
